### PR TITLE
Registration with same language and interface alert message added

### PR DESCRIPTION
**Pull request by despiritosanto**

### CODE REVIEW

**Comment by kumariswarnim** [comment]
**Change: **
Feature: Registration with interface and learning language macth
As Product owner
I want to show alert message to user when course and interface language macth
In order to assure that new users who wont accidentally chose the same course and interface language

**with **

Feature: Registration when interface languages is same as learning language
  As a Product owner
  I want to show an alert message to a user when course and interface language match
  In order to assure that interface language is not same as learning language

**Comment by kumariswarnim** [comment]
**Change:**

Scenario Outline: Confirm registration using the same course and interface language
    Given I navigate to landing page using <code>
    When I chose a learning language <flag_0>
    And I select the <country> of resident and <interface> language that same as learning language
    Then I should see a message to confirm that I am ok with this choice
    And I proceed with this choice
    And I proceed to splash by choosing default options
    Then I should login at application and see "splash" page

**with **

Scenario Outline: Confirm registration when course and interface language is same
    Given I navigate to landing page using <code>
    When I choose a learning language <flag_0>
    Then I should see a message to confirm that I am ok with this choice
    When I select YES
    Then I proceed to splash by choosing default options

**Comment by kumariswarnim** [comment]
**Change:**

Scenario Outline: No confirm registration using the same course and interface language
    Given I navigate to landing page using <code>
    When I chose a learning language <flag_0>
    And I select the <country> of resident and <interface> language that same as learning language
    Then I should see a message to confirm that I am ok with this choice
    And I dont confirm this choice and chose another learning language <flag_1>
    And I proceed to splash by choosing default options
    Then I should login at application and see "splash” page

**with**

 Scenario Outline: confirm registration when course and interface language is not same
    Given I navigate to landing page using <code>
    When I choose a learning language <flag_0>
    Then I should see a message to confirm that I am ok with this choice
    When I select NO and choose another  learning language <flag_1>
    Then I proceed to splash by choosing default options

**Comment by despiritosanto** [comment]
Fixed

**Pull request merged**
