### PR TITLE
B2B features added

### PR DESCRIPTION
**Pull request by despiritosanto**

### CODE REVIEW

**Comment by marcjones** [comment]
@despiritosanto Looking at the language used for these features, it would be better to be more declarative than imperative. For example:
```
And I type a correct <username> and <password> credential
And I click on Login button
```

This is implementation detail. Does the user have to use the login button? What happens if they hit return on the keyboard instead? What if in the future the login button is removed and we use fingerprints instead? This test would need to be updated even though the intent, which is just to log in, would be the same. To give better examples, I have rewritten the first feature file here:
```
Background
  Given I choose to login to busuuPro

Scenario: First time users see welcome message
  When I login for the first time
  Then I should see a welcome message
  When I proceed from the welcome message
  Then I should see my dashboard

Scenario Outline: Access for different user types:
  When I login as <user_type>
  Then I should have an option to view <view_types>

  Examples:
  | user_type  | view_types                                         |
  | admin      | students, instructors, classroom, courses, reports |
  | instructor | students, classroom, courses                       |
  | student    | students, classroom                                |

Scenario:
  When I submit invalid login details
  Then I should see an error message
```

Please can you try to write the features like this, describing user intentions instead of implementation detail.

**Comment by marcjones** [comment]
Also:

- I assume the "welcome" message is only displayed the first time you log in, so you'll see in my rewritten example that I specified this.

- Having username and password in feature files is just noise, so I replaced that with the user type which is what we're really interested in. You can store the user types we have in some data file like this:
```
users:
  admin:
    email: 'admin@busuu.com'
    password: 'testing123'

  student:
    email: 'student@busuu.com'
    password: 'testing123'

  invalid:
    email: 'invalid@example.com'
    password: 'invalid123'
```
This can live in a yaml file and then you can have a module with methods to get certain user types, like this:
```
module Users
  def Users.get_user(user_type)
    YAML.load_file("#{TEST_DATA_DIR}/users.yml")['users']["#{user_type} user"]
  end
end
```
Then in your step defs you just need to ```require``` the ```Users``` module and you can call 
```
When(/^I login as "(user_type)"$/) do | user_type |
  @user = Users.get_user user_type
  log_in_page.enter_email(@user['email'])
  log_in_page.enter_password(@user['password'])
  log_in_page.submit_credentials
end
```

This removes all the unnecessary usernames and passwords from the feature files.

**Comment by kumariswarnim** [comment]
I agree with Marc.

**Comment by marcjones** [comment]
Oh, and when you pass a string like this from feature file: ```students, instructors, classroom, courses, reports```

You can split by "," and put each substring into a list to compare with what tabs you see on the dashboard.

**Comment by despiritosanto** [comment]
Hey Marc, thanks for you contribuition!
I completly agree with you. I write the gherkings steps and also implement them, so why I tend to join user intentions with implementation detail. I'm going to try to think only on user side in this stage.

Using file for hiding the user credential, is a very good idea, I'll implent it when I start the implentation.

Thanks!

**Comment by marcjones** [comment]
Hey @despiritosanto 

Steps look much better, thanks for updating. One quick thing on this, the roles. It looks like everything is a benefit to product owner. E.g.
```
As Product owner
I want to perform login for admin/instructor/student who has already created their busuuPRO account
In order to ensure Login Functionality
```
But really we should be describing what the user wants. e.g.
```
As a busuuPro user
I want to be able to log in to my account
So that I can access my busuuPro account
```

**Comment by despiritosanto** [comment]
Done.

**Comment by marcjones** [comment]
👍

**Pull request merged**
